removed files from unsupported ports, i.e. Maemo and WebOS
navit-gps/navit pull request #1145
Opened 2021-09-07 19:32 UTC by hoehnp

When working on implementing a new download mechanism for maps, I noticed that we still have code for the currently unsupported and outdated platforms Maemo and WebOS in our repository. In order to clean up code, I suggest to remove this probably unmaintained code.

2021-09-07 20:43 UTC, metalstrolch commented
From my side good to go, I don't need those and as you stated they are probably unmaintained. Vote for delete.

2021-09-07 20:44 UTC, metalstrolch approved these changes

2021-09-13 09:24 UTC, hoehnp commented
Additionally I would also suggest to update the wiki to reflect that some of the platforms mentioned there are actually no longer actively maintained.

2021-09-13 12:04 UTC, jkoan requested changes
autoload/osso should probably be deleted as well. For sdl we could probably clean up the event System as well

2021-09-13 15:26 UTC, hoehnp commented on CMakeLists.txt
> -add_module(vehicle/maemo "Default" FALSE)
removed the lines, as requested.

2021-09-24 15:31 UTC, jkoan approved these changes

2021-09-26 17:55 UTC, merged