Rework the Binfile driver
navit-gps/navit pull request #1254
Opened 2023-12-27 21:47 UTC by jkoan

The binfile driver is probably our most important driver regarding map data. 

The driver should be split in multiple units that are as self contained as possible. This will also help with the understanding as currently the binfile map-driver mixes being a downloader, a zip implementation, a tile implementation and probably something else.

Things to take care of:

- [x] Remove Download Feature from Binfile driver
Why: It is completely undocumented and mixes data access via multiple ways. We want to focus on one thing only per Plugin
- [ ] Split Zipfile loading/access and loading of tile data
- [ ] Future extend on the documentation

2026-01-18 14:02 UTC, christf approved these changes
I like the removal. To make it build, I had to rebase it on top of the latest whitespace branch.

See https://github.com/christf/navit/tree/remove_binfile_download to see what I did.

2026-04-05 16:20 UTC, hoehnp commented
i found the functions while working on my cURL based downloader. Amazing that we had code for that in the bin driver. so I also agree with its removal.

2026-07-08 21:30 UTC, christf commented on navit/map/binfile/binfile.c
>      g_free(mr->url);
this should be removed along with the url field in the struct.

2026-07-08 21:31 UTC, christf requested changes
one minor gotcha: the url field is now unneded and can be let go, I think.

2026-09-03 21:24 UTC, christf requested changes
There are still two more fields that are unused now - I feel those should be removed to.

I do not think the callback list is actually used either but if we touch that then this changes signatures and I would stay clear of that for now. In any case, the url and version fields are now without use and I think we should let them go too.

2026-09-03 21:24 UTC, christf commented on navit/map/binfile/binfile.c
this is now dead too and I think it should be removed along with that g_free() in line 878

2026-09-03 21:24 UTC, christf commented on navit/map/binfile/binfile.c
>      int version;
with the removals from this PR, that field becomes unused. Let's remove it too.

2026-09-04 15:35 UTC, christf approved these changes

2026-09-04 15:39 UTC, merged